//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace main
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class accessContext : DbContext
    {
        public accessContext()
            : base("name=accessoriesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<accessierdetaile> accessierdetailes { get; set; }
        public virtual DbSet<accessierimage> accessierimages { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<CustomerProduct> CustomerProducts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<mobildetaile> mobildetailes { get; set; }
        public virtual DbSet<mobile_images> mobile_images { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
